name: Test

on:
  pull_request:

jobs:
  test:
    name: 'Test'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'

      - uses: pnpm/action-setup@v2.0.1
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7
          run_install: false

      - name: Cache pnpm store
        uses: actions/cache@v2
        with:
          path: |
            '/home/runner/.local/share/pnpm/store/v3'
            '/home/runner/.cache/Cypress'
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Turbo Cache
        id: turbo-cache
        uses: actions/cache@v2
        with:
          path: .turbo
          key: turbo-${{ github.job }}-${{ github.sha }}
          restore-keys: |
            turbo-${{ github.job }}-

      - name: Install
        run: pnpm i

      - name: Build all packages
        run: pnpm run build

      - name: Test
        run: pnpm run test

  cypress-prepare:
    name: 'Cypress prepare'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'

      - uses: pnpm/action-setup@v2.0.1
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7
          run_install: false

      - name: Cache pnpm store
        uses: actions/cache@v2
        with:
          path: |
            '/home/runner/.local/share/pnpm/store/v3'
            '/home/runner/.cache/Cypress'
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Cache build results
        uses: actions/cache@v2
        with:
          path: |
            */*/dist
            */*/lib
            */*/package
            */*/build
            */*/.next
            */*/.angular
            */*/.svelte-kit
            */*/dist-e2e
            */*/build-e2e
            testapps/gatsby/public
          key: e2e-build-${{ runner.os }}-${{ github.sha }}

      - name: Turbo Cache
        id: turbo-cache
        uses: actions/cache@v2
        with:
          path: .turbo
          key: turbo-${{ github.job }}-${{ github.sha }}
          restore-keys: |
            turbo-${{ github.job }}-

      - name: Install
        run: pnpm i

      - name: Build
        run: pnpm run build

      - name: Build e2e
        run: pnpm run build:e2e

      - id: set-dirs
        run: echo "::set-output name=dirs::$(ls | jq -R -s -c 'split("\n")[:-1]')"
        working-directory: e2e/cypress/integration

    outputs:
      dirs: ${{ steps.set-dirs.outputs.dirs }}

  cypress:
    name: 'Cypress'
    # cypress-prepare will install and build everything into cache
    needs: cypress-prepare
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        app: ${{ fromJson(needs.cypress-prepare.outputs.dirs) }}

    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'

      - uses: pnpm/action-setup@v2.0.1
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7
          run_install: false

      - name: Cache pnpm store
        uses: actions/cache@v2
        with:
          path: |
            '/home/runner/.local/share/pnpm/store/v3'
            '/home/runner/.cache/Cypress'
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Cache build results
        uses: actions/cache@v2
        with:
          path: |
            */*/dist
            */*/lib
            */*/package
            */*/build
            */*/.next
            */*/.angular
            */*/.svelte-kit
            */*/dist-e2e
            */*/build-e2e
            testapps/gatsby/public
          key: e2e-build-${{ runner.os }}-${{ github.sha }}

      - name: Install
        run: pnpm i

      - name: Cypress
        run: pnpm --prefix=e2e run start
        env:
          E2E_APP: ${{matrix.app}}

      - name: Cypress cleanup
        if: always()
        run: pnpm --prefix=e2e run services:stop

      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cypress
          path: |
            e2e/cypress/videos/**/*
            e2e/cypress/screenshots/**/*

  code-checks:
    name: Eslint 🪲
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'

      - uses: pnpm/action-setup@v2.0.1
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7
          run_install: false

      - name: Cache pnpm store
        uses: actions/cache@v2
        with:
          path: |
            '/home/runner/.local/share/pnpm/store/v3'
            '/home/runner/.cache/Cypress'
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Install
        run: pnpm i
        working-directory: ./

      - name: Eslint
        run: pnpm run eslint
        working-directory: ./
